### PR TITLE
fix(cli): Cannot find module 'graphql'

### LINKED ISSUE #1530: Cannot find module 'graphql'
**Version**: 0.14.0-alpha6

The CLI is not working in alpha6 because `graphql` is missing.

```
❯ npx graphback-cli@0.14.0-alpha6 init fullstack-issue           
npx: installed 521 in 28.088s
Cannot find module 'graphql'
Require stack:
- /home/ephelan/.npm/_npx/396521/lib/node_modules/graphback-cli/node_modules/@graphback/core/dist/crud/mappingHelpers.js
- /home/ephelan/.npm/_npx/396521/lib/node_modules/graphback-cli/node_modules/@graphback/core/dist/crud/index.js
- /home/ephelan/.npm/_npx/396521/lib/node_modules/graphback-cli/node_modules/@graphback/core/dist/index.js
- /home/ephelan/.npm/_npx/396521/lib/node_modules/graphback-cli/node_modules/graphback/dist/index.js
- /home/ephelan/.npm/_npx/396521/lib/node_modules/graphback-cli/dist/components/generate.js
- /home/ephelan/.npm/_npx/396521/lib/node_modules/graphback-cli/dist/components/index.js
- /home/ephelan/.npm/_npx/396521/lib/node_modules/graphback-cli/dist/index.js
```

This is because `generate` command uses the graphback package, which in turn looks for a peer dependency.

### PR DESCRIPTION
**Pull request by craicoverflow**
Fixes #1530 

`graphback-cli` exported all code from the `generate` command, which requires `graphql`.

This meant that the CLI would not work from any directory which is required for `init`.

To verify, run this command from a folder outside of Graphback (eg: $HOME)

Run `node <path/to/graphback>/packages/graphback-cli/dist/index.js init test`

It should work.

### CODE REVIEW

File: packages/graphback-cli/src/index.ts [hunk 1]
```diff
@@ -1,7 +1,6 @@
 #!/usr/bin/env node
 
 import * as yargs from 'yargs';
-export * from './components'
 export * from './config/graphbackExtension'
```
Comment (machi1990) [inline packages/graphback-cli/src/index.ts:4]: Is this needed too?

Comment (craicoverflow) [reply packages/graphback-cli/src/index.ts:4]: Nope, removing.
