### PR TITLE
fix(core): return resolvers as object

### LINKED ISSUE #1546: Graphback returns resolvers as array
When working with resolves we see that graphback resolvers are returned as array where most of the people will expect this to be just single object. Any reason why we have this. 

Most of the frameworks will return error when dealing with array.
[Error: "0" defined in resolvers, but not in schema]

### PR DESCRIPTION
**Pull request by craicoverflow**
Fixes #1546 #1556 

Returns resolvers as an object instead of an array.

### CODE REVIEW

File: templates/ts-apollo-postgres-backend/src/index.ts [hunk 1]
```diff
@@ -26,7 +27,10 @@ const db = connectDB()
 const dbConfig = loadDBConfig()
 
 const { typeDefs, resolvers, contextCreator } = buildGraphbackAPI(modelDefs, {
-  dataProviderCreator: createKnexDbProvider(db)
+  dataProviderCreator: createKnexDbProvider(db),
+  plugins: [
```
Comment (wtrocki) [inline templates/ts-apollo-postgres-backend/src/index.ts:31]: Let's remove it.

File: packages/graphback-core/src/plugin/GraphbackCoreMetadata.ts [hunk 2]
```diff
@@ -44,11 +44,15 @@ export class GraphbackCoreMetadata {
 
   public addResolvers(resolvers: IResolvers) {
     if (resolvers) {
-      this.resolvers.push(resolvers);
+      const mergedResolvers = [
+        this.resolvers,
+        resolvers
+      ]
+      this.resolvers = mergeResolvers(mergedResolvers)
```
Comment (wtrocki) [inline packages/graphback-core/src/plugin/GraphbackCoreMetadata.ts:51]: A kinda fancy version of Object.assign ;P

File: templates/ts-apollo-postgres-backend/src/index.ts (hunk 1 above)
Comment (craicoverflow) [reply templates/ts-apollo-postgres-backend/src/index.ts]: Done, put it in to test multiple sets of resolvers.

File: packages/graphback-core/src/plugin/GraphbackCoreMetadata.ts (hunk 2 above)
Comment (craicoverflow) [reply packages/graphback-core/src/plugin/GraphbackCoreMetadata.ts:51]: Object.assign does not merge deep, neither does the spread operator. So you would have to do:

```ts
this.resolvers = {
  Query: {
    ...this.resolvers.Query,
    ...resolvers.Query
  },
  Mutation: {
    ...this.resolvers.Mutation,
    ...resolvers.Mutation
  }
}
```

And it would get trickier trying to merge custom root resolvers.
