### PR TITLE
fix(graphql-migrations): migration failed for auto increments column

### LINKED ISSUE #2047: Second database migration throws an error
* **Module**: `graphql-migrations`
* **Version**: 0.16

This occurs when the primary key field is NOT "id" - it fails on `uuid: ID`, `_id: ID` etc.

```shell
> yarn develop
yarn run v1.22.5
$ ts-node src/index.ts
🚀  Server ready at http://localhost:4000/graphql
Migrated database
^C
> yarn develop
yarn run v1.22.5
$ ts-node src/index.ts
🚀  Server ready at http://localhost:4000/graphql
(node:71304) UnhandledPromiseRejectionWarning: error: alter table "public"."note" alter column "_id" drop not null - column "_id" is in a primary key
```

### PR DESCRIPTION
**Pull request by craicoverflow**
Fixes #2047 

Could not add a unit test for this because it is only a Postgres issue - we do need to think about integration tests for this scenario but due to it being a blocker we should get it merged and release first.

### CODE REVIEW

File: packages/graphql-migrations/src/connector/read.ts [hunk 1]
```diff
@@ -92,13 +93,13 @@ class Reader {
...
-          const {args, type} = getTypeAlias(info.type, info.maxLength);
+          const { args, type } = getTypeAlias(info.type, info.maxLength);
           const foreign = foreignKeys.find((k: any) => k.column === key);
-          const isPrimaryKey  = primaries.some((primary:  {column: string, indexName: string }) => primary.column === columnName);
+          const isPrimaryKey = primaries.some((primary: { column: string, indexName: string }) => primary.column === columnName);
           const column: TableColumn = {
             name: columnName,
             isPrimaryKey,
-            autoIncrementable: type === "increments" || type === "bigIncrements", // TODO
+            autoIncrementable: isAutoIncrementableColumn(this.config.client.toString(), info),
```
Comment (machi1990) [inline packages/graphql-migrations/src/connector/read.ts:102]:
```suggestion
            autoIncrementable: isPrimaryKey && isAutoIncrementableColumn(this.config.client.toString(), info),
```

**Comment by machi1990** [comment]
I've added one comment. I'll properly test this tomorrow.

File: packages/graphql-migrations/src/connector/read.ts (hunk 1 above)
Comment (craicoverflow) [reply packages/graphql-migrations/src/connector/read.ts:102]: What additional benefit will this bring? Non-primary key columns can also be auto-incrementing, so adding this check would ignore that.

File: packages/graphql-migrations/src/util/isAutoIncrementableColumn.ts [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+/**
+ * Detect if the column is incrementable based on column information
+ * 
+ * @param {string} client - database client 
+ * @param {Knex.ColumnInfo} columnInfo - metadata for column
+ */
+export function isAutoIncrementableColumn (client: string, columnInfo: Knex.ColumnInfo): boolean {
+  switch (client) {
+    case 'pg':
+      return columnInfo.defaultValue?.toString().startsWith('nextval(');
```
Comment (machi1990) [inline packages/graphql-migrations/src/util/isAutoIncrementableColumn.ts:12]: Should we check if the type is `integer` or `bigInteger` too? Because a `varchar` with a default value of `'nextval(dshdjhsjdh)'` whould be auto-incrementable too with this logic.

**Review by machi1990 — CHANGES_REQUESTED** [review]
> I've added one comment. I'll properly test this tomorrow.

I am still seeing the error

```log
alter table "public"."note" alter column "_id" drop not null - column "_id" is in a primary key
```

I used the postgres templates.

I guess it might be the fact that the the column in database has a default value while the parsed column from the schema does not. This does not go well with the diff computation.

File: packages/graphql-migrations/src/connector/read.ts (hunk 1 above)
Comment (machi1990) [reply packages/graphql-migrations/src/connector/read.ts:102]: You are right, but in our case I thought the auto-increment-ability was only handled for primary keys (worth checking) hence my suggestion. My worry is "if we allow other columns (from dbs) to be auto-incrementable while they are not when parsed from schema" could open another set of bugs with the diff algorithm.

File: packages/graphql-migrations/src/util/isAutoIncrementableColumn.ts (hunk 2 above)
Comment (craicoverflow) [reply packages/graphql-migrations/src/util/isAutoIncrementableColumn.ts:12]: My reasoning for not checking it is because this is what is being read from the remote database, and if the default value is `nextval('whatever')`  that is an error on the remote database and it should not handed by Postgres:

```sql
create table IF NOT EXISTS testtable (
	column1 varchar default nextval('xxxxx'),
	secondcol text
);
```

This throws:

```
ERROR:  relation "dshdjhsjdh" does not exist
SQL state: 42P01
```

I have also been able to successfully create a sequence and auto-incrementing logic on a varchar.

You can try it out here and see the auto-incrementing in action:

```sql
CREATE SEQUENCE if not exists testtable_id_seq;

create table IF NOT EXISTS testtable (
	column1 varchar default nextval("'testtable_id_seq'"),
	secondcol text
);

insert into testtable (secondcol) values ('hello');
```

The `testtable_id_seq` sequence is decoupled from the datatypes which use it, and "1", "2"... are also valid varchars so it works just fine.

**Comment by craicoverflow** [comment]
> I am still seeing the error

Weird, you  have run `yarn build`?

File: packages/graphql-migrations/src/connector/read.ts (hunk 1 above)
Comment (craicoverflow) [reply packages/graphql-migrations/src/connector/read.ts:102]: Yes, you are right about this. Thanks :+1:

File: packages/graphql-migrations/src/util/isAutoIncrementableColumn.ts (hunk 2 above)
Comment (machi1990) [reply packages/graphql-migrations/src/util/isAutoIncrementableColumn.ts:12]: Okay, thanks for the findings and great explanation. My reason was highly biased on `ID`as `integer`.  Sorry for the noise.

**Comment by machi1990** [comment]
> > I am still seeing the error
> 
> Weird, you have run `yarn build`?

Yes.

File: integration/tests/graphql-migrations-postgres.ts [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+
+test('consecutive migrations', async () => {
+  const model = buildSchema(`
+  """@model"""
+  type User {
+    """@id"""
+    _id: ID
+    name: String
+  }
+`)
```
Comment (machi1990) [inline integration/tests/graphql-migrations-postgres.ts:38]: <3 Thanks!

Comment (craicoverflow) [reply integration/tests/graphql-migrations-postgres.ts:38]: Not sure why you are still getting the error - your old database could have data in it that is preventing the column from being dropped.

**Comment by machi1990** [comment]
> > I've added one comment. I'll properly test this tomorrow.
> 
> I am still seeing the error
> 
> ```
> alter table "public"."note" alter column "_id" drop not null - column "_id" is in a primary key
> ```
> 
> I used the postgres templates.
> 
> I guess it might be the fact that the the column in database has a default value while the parsed column from the schema does not. This does not go well with the diff computation.

I was testing the first patch and forgot to rebase over the latest change you've made today. This seems to be no longer the issue and the PR fixes the problem. Thanks for driving this baby home :-)

**Review by machi1990 — APPROVED** [review]
